#if !canImport(ObjectiveC) && swift(<5.4)
import XCTest

extension InputDeviceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InputDeviceTests = [
        ("testEquatable", testEquatable),
        ("testEventConsumerHashable", testEventConsumerHashable),
        ("testEventParsing", testEventParsing),
        ("testMultipleEventsParsing", testMultipleEventsParsing),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(InputDeviceTests.__allTests__InputDeviceTests),
    ]
}
#endif
