#if !canImport(ObjectiveC)
import XCTest

extension DeviceInputTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeviceInputTests = [
        ("testNothing", testNothing),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DeviceInputTests.__allTests__DeviceInputTests),
    ]
}
#endif
